package:
  name: snakemakelib
  version: "0.1a.4"
source:
  git_rev: "0.1-alpha.4"
  git_url: https://github.com/percyfal/snakemakelib-core
requirements:
  build:
    - python >=3.4.3
    - setuptools
    - snakemake >=3.4.2
    - blaze
    - bokeh

  run:
    - python >=3.3
    - snakemake
    - pyyaml

test:
  requires:
    # docs
    - sphinx >=1.3.1
    - sphinx-bootstrap-theme
    - blaze
    - pandas
    - bokeh >=0.11.0

    # tests
    - coverage
    - flake8
    - pytest-cov ==1.8.1
    - pytest

  imports:
    - snakemake
    
about:
  home: https://github.com/percyfal/snakemakelib-core.git
  license: MIT License
  summary: 'snakemakelib core library'
  
