package:
  name: snakemakelib
  version: "0.1a.3"
source:
  git_rev: "0.1-alpha.3"
  git_url: https://github.com/percyfal/snakemakelib-core
requirements:
  build:
    - python ==3.4.3 # As with snakemake
    - setuptools
    - snakemake >=3.4.2

  run:
    - python >=3.3
    - snakemake
    - pyyaml
    - snakemakelib

test:
  requires:
    # docs
    - sphinx >=1.3.1
    - sphinx-bootstrap-theme

    # tests
    - coverage
    - flake8
    - mock
    - pytest
    - pytest-cov ==1.8.1
  imports:
    - snakemake
    
about:
  home: https://github.com/percyfal/snakemakelib-core.git
  license: MIT License
  summary: 'snakemakelib core library'
  
